### ISSUE TITLE
Custom email

### ISSUE THREAD

**Issue by itismujtaba** [aakash30jan/pydispo#2]
**Is there a way to generate custom email?**

**Comment by Arosado101** [comment]
I'm checking the code out and it seems that for this you go where you locate the random value for the username [Line43] is where you may select "input".  You may also throw a try and exception for 'Y' for custom input 'N' for random. choice.

**Comment by aakash30jan** [comment]
@itxmujtaba 
You can make use of `-e` flag for custom emails. For example, something like `pydispo -e foo-bar@1secmail.net`. If you want custom domains other than [these](https://www.1secmail.com/api/v1/?action=getDomainList), I am afraid it is not possible at the moment.
